version: '3.4'

networks:
  myRedDocker:

services:
  sqlServiceDocker:
    container_name: sql-server-docker
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - 8006:1433
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    networks:
        - myRedDocker
  

  backmedicos:
    build:
      context: .
      dockerfile: BackMedicos/Dockerfile
    networks:
        - myRedDocker
    depends_on:
        - sqlServiceDocker
    ports:
        - 5001:8081
    environment:
      - DB_HOST=sql-server-docker
      - DB_USER=sa
      - DB_PASSWORD=backAPI@@1995
      - DB_DATABASE_NAME=Customers
      - DB_TRUST_SERVER_CERTIFICATE=True
      - DB_CONNECTION_STRING=Server=${DB_HOST};Database=${DB_DATABASE_NAME};User=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=${DB_TRUST_SERVER_CERTIFICATE};
