version: '3.4'

networks:
  myRedDocker:

services:
  sqlServiceDocker:
    container_name: sql-server-docker
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - 8006:1433
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    networks:
        - myRedDocker
  

  backmedicos:
    build:
      context: .
      dockerfile: BackMedicos/Dockerfile
    networks:
        - myRedDocker
    depends_on:
        - sqlServiceDocker
    ports:
        - 5001:8081
    environment:
      - DB_CONNECTION_STRING=Server=sql-server-docker;Database=yourDB;User=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;
